### ISSUE TITLE
Why choose rvm over rbenv?

### ISSUE THREAD

**Issue by ia8k11** [FSFTN/ruby_installation#1]
I would like to know why only instructions for rvm is given. I prefer to put in instructions for both and leave the choice to the user. Or is there any specific reason for choosing rvm over rbenv?

**Comment by aravindgd** [comment]
There is no reason. If you have the time, give PR.

**Comment by rajanand02** [comment]
we are sending this instructions to colleges..rbenv is quite difficult to install when compare to rvm. this is just a temp file..we gonna standardise it..
